<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery("#foo").click(function(){
			jQuery.ajax({
				cache: true,
				async: true,
				dataType: 'json',
				type: 'GET',
				url: 'spaces/dGGiO6D1ir4B_BacwqjQWU/tickets/1',
				beforeSend: function(xhr) {
					xhr.setRequestHeader("Authorization", "Basic " + window.btoa("<?php echo $this->_api->getUserName(); ?>" + ":" + "<?php echo $this->_api->getPassword(); ?>") );
				},
				success: function(data) {
					
					console.log(data);

	
					setTimeout( function(){
	                    console.log("data");						
						data.custom_fields[0].value = "2012/03/23";

						jQuery.ajax({
							cache: true,
							async: true,
							dataType: 'json',
							type: 'PUT',
							data : data,
							url: 'spaces/dGGiO6D1ir4B_BacwqjQWU/tickets/1',
							beforeSend: function(xhr) {
								xhr.setRequestHeader("Authorization", "Basic " + window.btoa("<?php echo $this->_api->getUserName(); ?>" + ":" + "<?php echo $this->_api->getPassword(); ?>") );
							},
							success: function(resp) {
	                            console.log("response");
								console.log(resp);
							}
						});
					}, 3000);

				}
			});
		});
	});
</script>
</head>
<body>
<div id="foo" style="cursor:pointer;">FOO</div>
</body>
</html>
